Creating gameObject from UnitInfo. Now object you want to instantiate is null.
System.ArgumentException: The Object you want to instantiate is null.
  at UnityEngine.Object.CheckNullArgument (System.Object arg, System.String message) [0x00009] in /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnityEngineObject.bindings.cs:397
  at UnityEngine.Object.Instantiate (UnityEngine.Object original, UnityEngine.Transform parent, System.Boolean instantiateInWorldSpace) [0x00015] in /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnityEngineObject.bindings.cs:258
  at UnityEngine.Object.Instantiate[T] (T original, UnityEngine.Transform parent, System.Boolean worldPositionStays) [0x00001] in /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnityEngineObject.bindings.cs:296
  at ET.AfterUnitCreate_CreateUnitView+<Run>d__0.MoveNext () [0x00079] in /Users/hyperbola/Documents/GitHub/DiscoClient/Unity/Codes/HotfixView/Demo/Unit/AfterUnitCreate_CreateUnitView.cs:16
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <695d1cc93cca45069c528c15c9fdd749>:0
  at ET.ETTask.GetResult () [0x00039] in /Users/hyperbola/Documents/GitHub/DiscoClient/Unity/Assets/ThirdParty/ETTask/ETTask.cs:126
  at ET.AEvent`1+<Handle>d__2[A].MoveNext () [0x0002f] in /Users/hyperbola/Documents/GitHub/DiscoClient/Unity/Codes/Model/Core/Event/IEvent.cs:24
UnityEngine.Debug:LogError (object)
ET.UnityLogger:Error (string) (at Assets/Mono/Core/Log/UnityLogger.cs:30)
ET.Log:Error (System.Exception) (at Assets/Mono/Core/Log/Log.cs:88)
ET.AEvent`1/<Handle>d__2<ET.EventType.AfterUnitCreate>:MoveNext () (at Codes/Model/Core/Event/IEvent.cs:28)
ET.ETAsyncTaskMethodBuilder:Start<ET.AEvent`1/<Handle>d__2<ET.EventType.AfterUnitCreate>> (ET.AEvent`1/<Handle>d__2<ET.EventType.AfterUnitCreate>&) (at Assets/ThirdParty/ETTask/AsyncETTaskMethodBuilder.cs:57)
ET.AEvent`1<ET.EventType.AfterUnitCreate>:Handle (ET.EventType.AfterUnitCreate)
ET.EventSystem:Publish<ET.EventType.AfterUnitCreate> (ET.EventType.AfterUnitCreate) (at Codes/Model/Core/Object/EventSystem.cs:667)
ET.UnitFactory:Create (ET.Scene,ET.UnitInfo) (at Codes/Hotfix/Demo/Unit/UnitFactory.cs:44)
ET.SceneChangeHelper/<SceneChangeTo>d__0:MoveNext () (at Codes/Hotfix/Demo/Scene/SceneChangeHelper.cs:32)
ET.ETTask`1<ET.WaitType.Wait_all_sync>:SetResult (ET.WaitType.Wait_all_sync) (at Assets/ThirdParty/ETTask/ETTask.cs:295)
ET.ETAsyncTaskMethodBuilder`1<ET.WaitType.Wait_all_sync>:SetResult (ET.WaitType.Wait_all_sync) (at Assets/ThirdParty/ETTask/AsyncETTaskMethodBuilder.cs:94)
ET.ObjectWait/<Wait>d__3`1<ET.WaitType.Wait_all_sync>:MoveNext () (at Codes/Model/Core/ObjectWait.cs:110)
ET.ETTask`1<ET.WaitType.Wait_all_sync>:SetResult (ET.WaitType.Wait_all_sync) (at Assets/ThirdParty/ETTask/ETTask.cs:295)
ET.ObjectWait/ResultCallback`1<ET.WaitType.Wait_all_sync>:SetResult (ET.WaitType.Wait_all_sync) (at Codes/Model/Core/ObjectWait.cs:75)
ET.ObjectWait:Notify<ET.WaitType.Wait_all_sync> (ET.WaitType.Wait_all_sync) (at Codes/Model/Core/ObjectWait.cs:160)
ET.all_sync_s2c_handler/<Run>d__0:MoveNext () (at Codes/Hotfix/Demo/Unit/all_sync_s2c_handler.cs:12)
ET.ETAsyncTaskMethodBuilder:Start<ET.all_sync_s2c_handler/<Run>d__0> (ET.all_sync_s2c_handler/<Run>d__0&) (at Assets/ThirdParty/ETTask/AsyncETTaskMethodBuilder.cs:57)
ET.all_sync_s2c_handler:Run (ET.Session,ET.all_sync_s2c)
ET.AMHandler`1<ET.all_sync_s2c>:Handle (ET.Session,object) (at Codes/Model/Module/Message/AMHandler.cs:25)
ET.MessageDispatcherComponentHelper:Handle (ET.MessageDispatcherComponent,ET.Session,uint16,object) (at Codes/Hotfix/Module/Message/MessageDispatcherComponentSystem.cs:90)
ET.SessionStreamDispatcherClientOuter:Dispatch (ET.Session,System.IO.MemoryStream) (at Codes/Hotfix/Demo/Session/SessionStreamDispatcherClientOuter.cs:47)
ET.SessionStreamDispatcherSystem:Dispatch (ET.SessionStreamDispatcher,int,ET.Session,System.IO.MemoryStream) (at Codes/Hotfix/Module/Message/SessionStreamDispatcherSystem.cs:81)
ET.NetKcpComponentSystem:OnRead (ET.NetKcpComponent,long,System.IO.MemoryStream) (at Codes/Hotfix/Module/Message/NetKcpComponentSystem.cs:59)
ET.NetKcpComponentAwakeSystem/<>c__DisplayClass0_0:<Awake>b__1 (long,System.IO.MemoryStream) (at Codes/Hotfix/Module/Message/NetKcpComponentSystem.cs:16)
ET.AService:OnRead (long,System.IO.MemoryStream) (at Assets/Mono/Module/Network/AService.cs:53)
ET.TChannel:OnRead (System.IO.MemoryStream) (at Assets/Mono/Module/NetworkTCP/TChannel.cs:393)
ET.TChannel:HandleRecv (object) (at Assets/Mono/Module/NetworkTCP/TChannel.cs:281)
ET.TChannel:OnRecvComplete (object) (at Assets/Mono/Module/NetworkTCP/TChannel.cs:229)
ET.TChannel/<>c__DisplayClass10_0:<OnComplete>b__1 () (at Assets/Mono/Module/NetworkTCP/TChannel.cs:37)
ET.ThreadSynchronizationContext:Update () (at Assets/Mono/Core/ThreadSynchronizationContext.cs:34)
ET.Game:Update () (at Codes/Model/Core/Entity/Game.cs:38)
ET.Init:Update () (at Assets/Mono/MonoBehaviour/Init.cs:49)